### ISSUE TITLE
CloudFormation error

### ISSUE THREAD

**Issue by bakuteyev** [aws-samples/aws-ai-intelligent-document-processing#29]
Despite following the instructions closely, I'm encountering the following error on the first CloudFormation step.
`Template error: Unable to get mapping for RegionMap::me-central-1::datascience`
![2024-02-29_21-44-11](https://github.com/aws-samples/aws-ai-intelligent-document-processing/assets/26670285/f6574ea5-58ce-406b-9d93-db10dd55b748)

**Comment by bakuteyev** [comment]
Please add Middle East region to [yaml](https://github.com/aws-samples/aws-ai-intelligent-document-processing/blob/main/dist/idp-deploy.yaml)

**Comment by anjanvb** [comment]
Hi there. Thanks for the report. As far as I know Amazon Textract and Amazon Comprehend are not available in ME region as of yet. So it is unlikely that this repo will work in that region.

Here's the documentation for your reference-
https://docs.aws.amazon.com/general/latest/gr/textract.html
https://docs.aws.amazon.com/general/latest/gr/comprehend.html
