### ISSUE TITLE
02-idp-document-extraction-02.ipynb does not exist

### ISSUE THREAD

**Issue by ArlindNocaj** [aws-samples/aws-ai-intelligent-document-processing#5]
The last step in [module2 - doc extraction](https://catalog.us-east-1.prod.workshops.aws/workshops/c2af04b2-54ab-4b3d-be73-c7dd39074b20/en-US/02-getting-started/module-2-doc-extraction)
cannot performed since the file `02-idp-document-extraction-02.ipynb` does not exist.

Fix:
Add and execute the following lines in `02-idp-document-extraction.ipynb` to receive the notebook `02-idp-document-extraction-02.ipynb`

```
!wget 'https://github.com/aws-samples/amazon-textract-code-samples/raw/master/python/queries/insurance-card.ipynb' -O './02-idp-document-extraction-02.ipynb'
!wget 'https://github.com/aws-samples/amazon-textract-code-samples/raw/master/python/queries/insurance-card.png' -O './insurance-card.png'
```

**Comment by anjanvb** [comment]
This has been addressed. We now have a dedicated module 2 notebook.
